import java.util.ArrayList;
import java.util.List;

public class Dijkstra {

    public List Dijkstra(int nokta[],int karakter[]) {

        List<Vertex> graf = new ArrayList<>();

        Vertex vertexD1 = new Vertex("D1",0,3);
        Vertex vertexD2 = new Vertex("D2",0,10);
        Vertex vertexD3 = new Vertex("D3",5,0);
        Vertex vertexD4 = new Vertex("D4",10,3);
        Vertex vertexD5 = new Vertex("D5",1,1);
        Vertex vertexD6 = new Vertex("D6",1,2);
        Vertex vertexD7 = new Vertex("D7",1,3);
        Vertex vertexD8 = new Vertex("D8",1,4);
        Vertex vertexD9 = new Vertex("D9",1,6);
        Vertex vertexD10 = new Vertex("D10",1,7);
        Vertex vertexD11 = new Vertex("D11",1,8);
        Vertex vertexD12 = new Vertex("D12",1,9);
        Vertex vertexD13 = new Vertex("D13",1,10);
        Vertex vertexD14 = new Vertex("D14",1,11);
        Vertex vertexD15 = new Vertex("D15",2,1);
        Vertex vertexD16 = new Vertex("D16",2,3);
        Vertex vertexD17 = new Vertex("D17",2,4);
        Vertex vertexD18 = new Vertex("D18",2,5);
        Vertex vertexD19 = new Vertex("D19",2,6);
        Vertex vertexD20 = new Vertex("D20",2,7);
        Vertex vertexD21 = new Vertex("D21",2,8);
        Vertex vertexD22 = new Vertex("D22",2,11);
        Vertex vertexD23 = new Vertex("D23",3,1);
        Vertex vertexD24 = new Vertex("D24",3,2);
        Vertex vertexD25 = new Vertex("D25",3,3);
        Vertex vertexD26 = new Vertex("D26",3,4);
        Vertex vertexD27 = new Vertex("D27",3,6);
        Vertex vertexD28 = new Vertex("D28",3,8);
        Vertex vertexD29 = new Vertex("D29",3,9);
        Vertex vertexD30 = new Vertex("D30",3,11);
        Vertex vertexD31 = new Vertex("D31",4,1);
        Vertex vertexD32 = new Vertex("D32",4,3);
        Vertex vertexD33 = new Vertex("D33",4,6);
        Vertex vertexD34 = new Vertex("D34",4,8);
        Vertex vertexD35 = new Vertex("D35",4,11);
        Vertex vertexD36 = new Vertex("D36",5,1);
        Vertex vertexD37 = new Vertex("D37",5,3);
        Vertex vertexD38 = new Vertex("D38",5,4);
        Vertex vertexD39 = new Vertex("D39",5,5);
        Vertex vertexD40 = new Vertex("D40",5,6);
        Vertex vertexD41 = new Vertex("D41",5,8);
        Vertex vertexD42 = new Vertex("D42",5,10);
        Vertex vertexD43 = new Vertex("D43",5,11);
        Vertex vertexD44 = new Vertex("D44",6,1);
        Vertex vertexD45 = new Vertex("D45",6,4);
        Vertex vertexD46 = new Vertex("D46",6,5);
        Vertex vertexD47 = new Vertex("D47",6,6);
        Vertex vertexD48 = new Vertex("D48",6,8);
        Vertex vertexD49 = new Vertex("D49",6,9);
        Vertex vertexD50 = new Vertex("D50",6,10);
        Vertex vertexD51 = new Vertex("D51",6,11);
        Vertex vertexD52 = new Vertex("D52",7,1);
        Vertex vertexD53 = new Vertex("D53",7,3);
        Vertex vertexD54 = new Vertex("D54",7,4);
        Vertex vertexD55 = new Vertex("D55",7,5);
        Vertex vertexD56 = new Vertex("D56",7,6);
        Vertex vertexD57 = new Vertex("D57",7,7);
        Vertex vertexD58 = new Vertex("D58",7,8);
        Vertex vertexD59 = new Vertex("D59",7,9);
        Vertex vertexD60 = new Vertex("D60",7,10);
        Vertex vertexD61 = new Vertex("D61",7,11);
        Vertex vertexD62 = new Vertex("D62",8,1);
        Vertex vertexD63 = new Vertex("D63",8,3);
        Vertex vertexD64 = new Vertex("D64",8,9);
        Vertex vertexD65 = new Vertex("D65",8,10);
        Vertex vertexD66 = new Vertex("D66",8,11);
        Vertex vertexD67 = new Vertex("D67",9,1);
        Vertex vertexD68 = new Vertex("D68",9,2);
        Vertex vertexD69 = new Vertex("D69",9,3);
        Vertex vertexD70 = new Vertex("D70",9,4);
        Vertex vertexD71 = new Vertex("D71",9,5);
        Vertex vertexD72 = new Vertex("D72",9,6);
        Vertex vertexD73 = new Vertex("D73",9,7);
        Vertex vertexD74 = new Vertex("D74",9,8);
        Vertex vertexD75 = new Vertex("D75",9,9);
        Vertex vertexD76 = new Vertex("D76",9,10);
        Vertex vertexD77 = new Vertex("D77",9,11);
        Vertex vertexD78 = new Vertex("D78",7,12);

        graf.add(vertexD1);
        graf.add(vertexD2);
        graf.add(vertexD3);
        graf.add(vertexD4);
        graf.add(vertexD5);
        graf.add(vertexD6);
        graf.add(vertexD7);
        graf.add(vertexD8);
        graf.add(vertexD9);
        graf.add(vertexD10);
        graf.add(vertexD11);
        graf.add(vertexD12);
        graf.add(vertexD13);
        graf.add(vertexD14);
        graf.add(vertexD15);
        graf.add(vertexD16);
        graf.add(vertexD17);
        graf.add(vertexD18);
        graf.add(vertexD19);
        graf.add(vertexD20);
        graf.add(vertexD21);
        graf.add(vertexD22);
        graf.add(vertexD23);
        graf.add(vertexD24);
        graf.add(vertexD25);
        graf.add(vertexD26);
        graf.add(vertexD27);
        graf.add(vertexD28);
        graf.add(vertexD29);
        graf.add(vertexD30);
        graf.add(vertexD31);
        graf.add(vertexD32);
        graf.add(vertexD33);
        graf.add(vertexD34);
        graf.add(vertexD35);
        graf.add(vertexD36);
        graf.add(vertexD37);
        graf.add(vertexD38);
        graf.add(vertexD39);
        graf.add(vertexD40);
        graf.add(vertexD41);
        graf.add(vertexD42);
        graf.add(vertexD43);
        graf.add(vertexD44);
        graf.add(vertexD45);
        graf.add(vertexD46);
        graf.add(vertexD47);
        graf.add(vertexD48);
        graf.add(vertexD49);
        graf.add(vertexD50);
        graf.add(vertexD51);
        graf.add(vertexD52);
        graf.add(vertexD53);
        graf.add(vertexD54);
        graf.add(vertexD55);
        graf.add(vertexD56);
        graf.add(vertexD57);
        graf.add(vertexD58);
        graf.add(vertexD59);
        graf.add(vertexD60);
        graf.add(vertexD61);
        graf.add(vertexD62);
        graf.add(vertexD63);
        graf.add(vertexD64);
        graf.add(vertexD65);
        graf.add(vertexD66);
        graf.add(vertexD67);
        graf.add(vertexD68);
        graf.add(vertexD69);
        graf.add(vertexD70);
        graf.add(vertexD71);
        graf.add(vertexD72);
        graf.add(vertexD73);
        graf.add(vertexD74);
        graf.add(vertexD75);
        graf.add(vertexD76);
        graf.add(vertexD77);
        graf.add(vertexD78);

        int baslangic=0;
        int bitis=0;
        for (int i = 0; i <78 ; i++) {
           if(graf.get(i).getVertexX()==nokta[0]&&graf.get(i).getVertexY()==nokta[1]){

               baslangic=i;
           }
           else if(graf.get(i).getVertexX()==karakter[0]&&graf.get(i).getVertexY()==karakter[1]){

                bitis=i;
            }
        }


        vertexD1.addNeighbour(new Edge(1,vertexD1,vertexD7));
        vertexD2.addNeighbour(new Edge(1,vertexD2,vertexD13));
        vertexD3.addNeighbour(new Edge(1,vertexD3,vertexD36));
        vertexD4.addNeighbour(new Edge(1,vertexD4,vertexD69));
        vertexD5.addNeighbour(new Edge(1,vertexD5,vertexD6));
        vertexD5.addNeighbour(new Edge(1,vertexD5,vertexD15));
        vertexD6.addNeighbour(new Edge(1,vertexD6,vertexD5));
        vertexD6.addNeighbour(new Edge(1,vertexD6,vertexD7));
        vertexD7.addNeighbour(new Edge(1,vertexD7,vertexD6));
        vertexD7.addNeighbour(new Edge(1,vertexD7,vertexD8));
        vertexD7.addNeighbour(new Edge(1,vertexD7,vertexD16));
        vertexD8.addNeighbour(new Edge(1,vertexD8,vertexD7));
        vertexD8.addNeighbour(new Edge(1,vertexD8,vertexD17));
        vertexD9.addNeighbour(new Edge(1,vertexD9,vertexD10));
        vertexD9.addNeighbour(new Edge(1,vertexD9,vertexD19));
        vertexD10.addNeighbour(new Edge(1,vertexD10,vertexD9));
        vertexD10.addNeighbour(new Edge(1,vertexD10,vertexD11));
        vertexD10.addNeighbour(new Edge(1,vertexD10,vertexD20));
        vertexD11.addNeighbour(new Edge(1,vertexD11,vertexD12));
        vertexD11.addNeighbour(new Edge(1,vertexD11,vertexD10));
        vertexD11.addNeighbour(new Edge(1,vertexD11,vertexD21));
        vertexD12.addNeighbour(new Edge(1,vertexD12,vertexD13));
        vertexD12.addNeighbour(new Edge(1,vertexD12,vertexD11));
        vertexD13.addNeighbour(new Edge(1,vertexD13,vertexD2));
        vertexD13.addNeighbour(new Edge(1,vertexD13,vertexD12));
        vertexD13.addNeighbour(new Edge(1,vertexD13,vertexD14));
        vertexD14.addNeighbour(new Edge(1,vertexD14,vertexD13));
        vertexD14.addNeighbour(new Edge(1,vertexD14,vertexD22));
        vertexD15.addNeighbour(new Edge(1,vertexD15,vertexD23));
        vertexD15.addNeighbour(new Edge(1,vertexD15,vertexD5));
        vertexD16.addNeighbour(new Edge(1,vertexD16,vertexD17));
        vertexD16.addNeighbour(new Edge(1,vertexD16,vertexD7));
        vertexD16.addNeighbour(new Edge(1,vertexD16,vertexD25));
        vertexD17.addNeighbour(new Edge(1,vertexD17,vertexD16));
        vertexD17.addNeighbour(new Edge(1,vertexD17,vertexD18));
        vertexD17.addNeighbour(new Edge(1,vertexD17,vertexD8));
        vertexD17.addNeighbour(new Edge(1,vertexD17,vertexD26));
        vertexD18.addNeighbour(new Edge(1,vertexD18,vertexD19));
        vertexD18.addNeighbour(new Edge(1,vertexD18,vertexD17));
        vertexD19.addNeighbour(new Edge(1,vertexD19,vertexD18));
        vertexD19.addNeighbour(new Edge(1,vertexD19,vertexD9));
        vertexD19.addNeighbour(new Edge(1,vertexD19,vertexD20));
        vertexD19.addNeighbour(new Edge(1,vertexD19,vertexD27));
        vertexD20.addNeighbour(new Edge(1,vertexD20,vertexD19));
        vertexD20.addNeighbour(new Edge(1,vertexD20,vertexD21));
        vertexD20.addNeighbour(new Edge(1,vertexD20,vertexD10));
        vertexD21.addNeighbour(new Edge(1,vertexD21,vertexD20));
        vertexD21.addNeighbour(new Edge(1,vertexD21,vertexD28));
        vertexD21.addNeighbour(new Edge(1,vertexD21,vertexD11));
        vertexD22.addNeighbour(new Edge(1,vertexD22,vertexD14));
        vertexD22.addNeighbour(new Edge(1,vertexD22,vertexD30));
        vertexD23.addNeighbour(new Edge(1,vertexD23,vertexD15));
        vertexD23.addNeighbour(new Edge(1,vertexD23,vertexD24));
        vertexD23.addNeighbour(new Edge(1,vertexD23,vertexD31));
        vertexD24.addNeighbour(new Edge(1,vertexD24,vertexD23));
        vertexD24.addNeighbour(new Edge(1,vertexD24,vertexD25));
        vertexD25.addNeighbour(new Edge(1,vertexD25,vertexD24));
        vertexD25.addNeighbour(new Edge(1,vertexD25,vertexD16));
        vertexD25.addNeighbour(new Edge(1,vertexD25,vertexD26));
        vertexD25.addNeighbour(new Edge(1,vertexD25,vertexD32));
        vertexD26.addNeighbour(new Edge(1,vertexD26,vertexD25));
        vertexD26.addNeighbour(new Edge(1,vertexD26,vertexD17));
        vertexD27.addNeighbour(new Edge(1,vertexD27,vertexD19));
        vertexD27.addNeighbour(new Edge(1,vertexD27,vertexD33));
        vertexD28.addNeighbour(new Edge(1,vertexD28,vertexD21));
        vertexD28.addNeighbour(new Edge(1,vertexD28,vertexD29));
        vertexD28.addNeighbour(new Edge(1,vertexD28,vertexD34));
        vertexD29.addNeighbour(new Edge(1,vertexD29,vertexD28));
        vertexD30.addNeighbour(new Edge(1,vertexD30,vertexD22));
        vertexD30.addNeighbour(new Edge(1,vertexD30,vertexD35));
        vertexD31.addNeighbour(new Edge(1,vertexD31,vertexD23));
        vertexD31.addNeighbour(new Edge(1,vertexD31,vertexD36));
        vertexD32.addNeighbour(new Edge(1,vertexD32,vertexD25));
        vertexD32.addNeighbour(new Edge(1,vertexD32,vertexD37));
        vertexD33.addNeighbour(new Edge(1,vertexD33,vertexD27));
        vertexD33.addNeighbour(new Edge(1,vertexD33,vertexD40));
        vertexD34.addNeighbour(new Edge(1,vertexD34,vertexD28));
        vertexD34.addNeighbour(new Edge(1,vertexD34,vertexD41));
        vertexD35.addNeighbour(new Edge(1,vertexD35,vertexD30));
        vertexD35.addNeighbour(new Edge(1,vertexD35,vertexD43));
        vertexD36.addNeighbour(new Edge(1,vertexD36,vertexD31));
        vertexD36.addNeighbour(new Edge(1,vertexD36,vertexD44));
        vertexD37.addNeighbour(new Edge(1,vertexD37,vertexD32));
        vertexD37.addNeighbour(new Edge(1,vertexD37,vertexD38));
        vertexD38.addNeighbour(new Edge(1,vertexD38,vertexD37));
        vertexD38.addNeighbour(new Edge(1,vertexD38,vertexD39));
        vertexD38.addNeighbour(new Edge(1,vertexD38,vertexD45));
        vertexD39.addNeighbour(new Edge(1,vertexD39,vertexD38));
        vertexD39.addNeighbour(new Edge(1,vertexD39,vertexD40));
        vertexD39.addNeighbour(new Edge(1,vertexD39,vertexD46));
        vertexD40.addNeighbour(new Edge(1,vertexD40,vertexD33));
        vertexD40.addNeighbour(new Edge(1,vertexD40,vertexD39));
        vertexD40.addNeighbour(new Edge(1,vertexD40,vertexD47));
        vertexD41.addNeighbour(new Edge(1,vertexD41,vertexD34));
        vertexD41.addNeighbour(new Edge(1,vertexD41,vertexD48));
        vertexD42.addNeighbour(new Edge(1,vertexD42,vertexD43));
        vertexD42.addNeighbour(new Edge(1,vertexD42,vertexD50));
        vertexD43.addNeighbour(new Edge(1,vertexD43,vertexD35));
        vertexD43.addNeighbour(new Edge(1,vertexD43,vertexD42));
        vertexD43.addNeighbour(new Edge(1,vertexD43,vertexD51));
        vertexD44.addNeighbour(new Edge(1,vertexD44,vertexD36));
        vertexD44.addNeighbour(new Edge(1,vertexD44,vertexD52));
        vertexD45.addNeighbour(new Edge(1,vertexD45,vertexD38));
        vertexD45.addNeighbour(new Edge(1,vertexD45,vertexD46));
        vertexD45.addNeighbour(new Edge(1,vertexD45,vertexD54));
        vertexD46.addNeighbour(new Edge(1,vertexD46,vertexD39));
        vertexD46.addNeighbour(new Edge(1,vertexD46,vertexD45));
        vertexD46.addNeighbour(new Edge(1,vertexD46,vertexD47));
        vertexD46.addNeighbour(new Edge(1,vertexD46,vertexD55));
        vertexD47.addNeighbour(new Edge(1,vertexD47,vertexD40));
        vertexD47.addNeighbour(new Edge(1,vertexD47,vertexD46));
        vertexD47.addNeighbour(new Edge(1,vertexD47,vertexD56));
        vertexD48.addNeighbour(new Edge(1,vertexD48,vertexD41));
        vertexD48.addNeighbour(new Edge(1,vertexD48,vertexD49));
        vertexD48.addNeighbour(new Edge(1,vertexD48,vertexD58));
        vertexD49.addNeighbour(new Edge(1,vertexD49,vertexD48));
        vertexD49.addNeighbour(new Edge(1,vertexD49,vertexD50));
        vertexD49.addNeighbour(new Edge(1,vertexD49,vertexD59));
        vertexD50.addNeighbour(new Edge(1,vertexD50,vertexD42));
        vertexD50.addNeighbour(new Edge(1,vertexD50,vertexD49));
        vertexD50.addNeighbour(new Edge(1,vertexD50,vertexD51));
        vertexD50.addNeighbour(new Edge(1,vertexD50,vertexD60));
        vertexD51.addNeighbour(new Edge(1,vertexD51,vertexD43));
        vertexD51.addNeighbour(new Edge(1,vertexD51,vertexD50));
        vertexD51.addNeighbour(new Edge(1,vertexD51,vertexD61));
        vertexD52.addNeighbour(new Edge(1,vertexD52,vertexD44));
        vertexD52.addNeighbour(new Edge(1,vertexD52,vertexD62));
        vertexD53.addNeighbour(new Edge(1,vertexD53,vertexD54));
        vertexD53.addNeighbour(new Edge(1,vertexD53,vertexD63));
        vertexD54.addNeighbour(new Edge(1,vertexD54,vertexD45));
        vertexD54.addNeighbour(new Edge(1,vertexD54,vertexD53));
        vertexD54.addNeighbour(new Edge(1,vertexD54,vertexD55));
        vertexD55.addNeighbour(new Edge(1,vertexD55,vertexD54));
        vertexD55.addNeighbour(new Edge(1,vertexD55,vertexD46));
        vertexD55.addNeighbour(new Edge(1,vertexD55,vertexD56));
        vertexD56.addNeighbour(new Edge(1,vertexD56,vertexD55));
        vertexD56.addNeighbour(new Edge(1,vertexD56,vertexD47));
        vertexD56.addNeighbour(new Edge(1,vertexD56,vertexD57));
        vertexD57.addNeighbour(new Edge(1,vertexD57,vertexD56));
        vertexD57.addNeighbour(new Edge(1,vertexD57,vertexD58));
        vertexD58.addNeighbour(new Edge(1,vertexD58,vertexD57));
        vertexD58.addNeighbour(new Edge(1,vertexD58,vertexD48));
        vertexD58.addNeighbour(new Edge(1,vertexD58,vertexD59));
        vertexD59.addNeighbour(new Edge(1,vertexD59,vertexD58));
        vertexD59.addNeighbour(new Edge(1,vertexD59,vertexD49));
        vertexD59.addNeighbour(new Edge(1,vertexD59,vertexD64));
        vertexD59.addNeighbour(new Edge(1,vertexD59,vertexD60));
        vertexD60.addNeighbour(new Edge(1,vertexD60,vertexD50));
        vertexD60.addNeighbour(new Edge(1,vertexD60,vertexD59));
        vertexD60.addNeighbour(new Edge(1,vertexD60,vertexD61));
        vertexD60.addNeighbour(new Edge(1,vertexD60,vertexD65));
        vertexD61.addNeighbour(new Edge(1,vertexD61,vertexD51));
        vertexD61.addNeighbour(new Edge(1,vertexD61,vertexD60));
        vertexD61.addNeighbour(new Edge(1,vertexD61,vertexD78));
        vertexD61.addNeighbour(new Edge(1,vertexD61,vertexD66));
        vertexD62.addNeighbour(new Edge(1,vertexD62,vertexD52));
        vertexD62.addNeighbour(new Edge(1,vertexD62,vertexD67));
        vertexD63.addNeighbour(new Edge(1,vertexD63,vertexD53));
        vertexD63.addNeighbour(new Edge(1,vertexD63,vertexD69));
        vertexD64.addNeighbour(new Edge(1,vertexD64,vertexD59));
        vertexD64.addNeighbour(new Edge(1,vertexD64,vertexD65));
        vertexD64.addNeighbour(new Edge(1,vertexD64,vertexD75));
        vertexD65.addNeighbour(new Edge(1,vertexD65,vertexD60));
        vertexD65.addNeighbour(new Edge(1,vertexD65,vertexD64));
        vertexD65.addNeighbour(new Edge(1,vertexD65,vertexD66));
        vertexD65.addNeighbour(new Edge(1,vertexD65,vertexD76));
        vertexD66.addNeighbour(new Edge(1,vertexD66,vertexD61));
        vertexD66.addNeighbour(new Edge(1,vertexD66,vertexD65));
        vertexD66.addNeighbour(new Edge(1,vertexD66,vertexD77));
        vertexD67.addNeighbour(new Edge(1,vertexD67,vertexD62));
        vertexD67.addNeighbour(new Edge(1,vertexD67,vertexD68));
        vertexD68.addNeighbour(new Edge(1,vertexD68,vertexD67));
        vertexD68.addNeighbour(new Edge(1,vertexD68,vertexD69));
        vertexD69.addNeighbour(new Edge(1,vertexD69,vertexD63));
        vertexD69.addNeighbour(new Edge(1,vertexD69,vertexD68));
        vertexD69.addNeighbour(new Edge(1,vertexD69,vertexD70));
        vertexD70.addNeighbour(new Edge(1,vertexD70,vertexD69));
        vertexD70.addNeighbour(new Edge(1,vertexD70,vertexD71));
        vertexD71.addNeighbour(new Edge(1,vertexD71,vertexD70));
        vertexD71.addNeighbour(new Edge(1,vertexD71,vertexD72));
        vertexD72.addNeighbour(new Edge(1,vertexD72,vertexD71));
        vertexD72.addNeighbour(new Edge(1,vertexD72,vertexD73));
        vertexD73.addNeighbour(new Edge(1,vertexD73,vertexD72));
        vertexD73.addNeighbour(new Edge(1,vertexD73,vertexD74));
        vertexD74.addNeighbour(new Edge(1,vertexD74,vertexD73));
        vertexD74.addNeighbour(new Edge(1,vertexD74,vertexD75));
        vertexD75.addNeighbour(new Edge(1,vertexD75,vertexD64));
        vertexD75.addNeighbour(new Edge(1,vertexD75,vertexD74));
        vertexD75.addNeighbour(new Edge(1,vertexD75,vertexD76));
        vertexD76.addNeighbour(new Edge(1,vertexD76,vertexD75));
        vertexD76.addNeighbour(new Edge(1,vertexD76,vertexD77));
        vertexD76.addNeighbour(new Edge(1,vertexD76,vertexD65));
        vertexD77.addNeighbour(new Edge(1,vertexD77,vertexD66));
        vertexD77.addNeighbour(new Edge(1,vertexD77,vertexD76));


        DijkstraShortestPath shortestPath1 = new DijkstraShortestPath();
        shortestPath1.computeShortestPaths(graf.get(baslangic));


        List<Vertex> dugumler = new ArrayList<>();
        dugumler=shortestPath1.getShortestPathTo(graf.get(bitis));



return dugumler;
    }
}
